#!/bin/env python

import core
from scan import Scanner

# Base de datos donde se guardan los puertos abiertos
dbTCP = {}
dbUDP = {}
commonPorts = ('21','22','25','135','902','80','110','143','443','587','3306','27017')

def main(target):

    sc = Scanner()
    for port in commonPorts:
        if sc.simple(target,port,'tcp') == True:
        	print('Puerto TCP: '+port)
        	print("------------TCP MEDIO------------")
        	print(sc.start(target,port,'tcp'))
        	print("------------TCP ALTO------------")
        	print(sc.start(target,port,'tcpH'))

        if sc.simple(target,port,'udp') == True:
        	print('Puerto UDP: '+port)
        	print("------------UDP MEDIO------------")
        	print(sc.start(target,port,'udp'))
        	print("------------UDP ALTO------------")
        	print(sc.start(target,port,'udpH'))
        # escaners medios dsjoaghladsglkadsg


if __name__ == '__main__':
    target = '127.0.0.1'
    main(target)