#!/bin/env python

import core
from scan import Scanner

# VARIABLES GLOBALES
commonPorts = ('8888','3306')

def main(target):
# Desde la función main se lanzan las tareas generales
# All TCP ports
	for port in commonPorts:
		taskLauncher(target,port,'tcp')

	for port in commonPorts:
		taskLauncher(target,port,'udp')


def taskLauncher(target,port,protocol):
	sc = Scanner()
	if(sc.simple(target,port,protocol)):
		dataManager(target, port, protocol, 'medium',sc.start(target,port,protocol))
		dataManager(target, port, protocol, 'high', sc.start(target,port,protocol+'H'))


def dataManager(target,port,protocol, task, data):
	# escritura de datos
	print(data)

# def screenManager():


if __name__ == '__main__':
	target = '127.0.0.1'
	main(target)