#!/bin/env python

import core
from scan import Scanner

# Base de datos donde se guardan los puertos abiertos
dbTCP = {}
dbUDP = {}
commonPorts = ('135','902','80','443','21','22','25','80','110','143','443','587','3306','27017')

def main(target):

    sc = Scanner()
    
    for port in commonPorts:
        sc.simpleTCP(target,port)

        # escaners medios dsjoaghladsglkadsg


if __name__ == '__main__':
    target = '127.0.0.1'
    main(target)